spring:
  main:
    web-application-type: reactive
  redis:
    host: 10.16.64.250
    port: 6379

  cloud:
    gateway:
      routes:
        - id: author_route
          uri: lb://art-dev-author
          predicates:
            - Path=/api/author/**,/hello
          filters:
            - RewritePath=/api/author/(?<segment>.*),/author/$\{segment}

        - id: notice_route
          uri: lb://art-market-notice
          predicates:
            - Path=/api/notice/**
          filters:
            - RewritePath=/api/notice/(?<segment>/?.*),/$\{segment}

        - id: order_route
          uri: lb://art-order-server
          predicates:
            - Path=/api/order/**
          filters:
            - RewritePath=/api/order/(?<segment>/?.*),/$\{segment}

        - id: sms_route
          uri: lb://art-market-sms
          predicates:
            - Path=/api/sms/**
          filters:
            - RewritePath=/api/sms/(?<segment>/?.*),/$\{segment}

        - id: seckill_route
          uri: lb://art-market-seckill
          predicates:
            - Path=/app/seckill/**
          filters:
            - RewritePath=/app/seckill/(?<segment>/?.*),/$\{segment}
#            - name: RequestRateLimiter
#              args:
#                redis-rate-limiter.replenishRate: 3
#                redis-rate-limiter.burstCapacity: 2000
#                key-resolver: "#{@userKeyResolver}"


        - id: trade_route
          uri: lb://art-market-trade
          predicates:
            - Path=/api/trade/**
          filters:
            - RewritePath=/api/trade/(?<segment>/?.*),/$\{segment}

        - id: memeber_route
          uri: lb://art-user-service
          predicates:
            - Path=/api/user/**
          filters:
            - RewritePath=/api/user(?<segment>.*),/$\{segment}

